apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-server
  namespace: platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: es-server
    spec:
      containers:
        - name: es-server
          imagePullPolicy: IfNotPresent
          image: registry.cn-hangzhou.aliyuncs.com/wuyufeng/images
          
          command: ["/bin/sh","-c", "usr/share/elasticsearch/bin/elasticsearch"]
          ports:
            - containerPort: 9200
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: platform-hostdisk
            
        - name: tz-config
          hostPath:
            path: /etc/localtime

        

---
apiVersion: v1
kind: Service
metadata:
  name: es-server
  namespace: platform
spec:
  type: NodePort 
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: "elasticsearch"
    nodePort: 30057
  selector:
    app: es-server